general {
    # Saturated, vibrant multi-color gradient for the active window
    col.active_border = rgb(390B2B) rgb(2C2C77) rgb(532302) rgb(871A2D) rgb(9F5A24) rgb(F97710) 45deg
    # Dimmed, mostly transparent color for background windows
    col.inactive_border = rgba(03060Cee)
}
