# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #EA7BA7

background #040409
foreground #FF70FF

color0 #05050C
color1 #848BBC
color2 #7EA165
color3 #D2526B
color4 #41B8BC
color5 #D68750
color6 #C104C3
color7 #FF5BFF
color8 #BF00C1
color9 #848BBC
color10 #7EA165
color11 #D2526B
color12 #41B8BC
color13 #D68750
color14 #C104C3
color15 #F7A5F7

mark1_foreground #C103C3
mark2_foreground #FF49FF
mark3_foreground #C103C3
