# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #A09CD8

background #030409
foreground #FFBAF4

color0 #04050B
color1 #010F34
color2 #354386
color3 #6B3765
color4 #856FAB
color5 #407EBC
color6 #D78BC2
color7 #FFAFE8
color8 #B26B9F
color9 #010F34
color10 #354386
color11 #6B3765
color12 #856FAB
color13 #407EBC
color14 #D78BC2
color15 #F7CEEB

mark1_foreground #D76FBA
mark2_foreground #FF8CDE
mark3_foreground #D76FBA
