# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #D3A75C

background #010603
foreground #FFCD5F

color0 #020705
color1 #24242B
color2 #3F5A60
color3 #614C36
color4 #77877F
color5 #A68059
color6 #F3A63C
color7 #FFC457
color8 #C07B0C
color9 #24242B
color10 #3F5A60
color11 #614C36
color12 #77877F
color13 #A68059
color14 #F3A63C
color15 #F7D9A2

mark1_foreground #F3A130
mark2_foreground #FFBE46
mark3_foreground #F3A130
